from __future__ import annotations

from pathlib import Path

DEFAULT_BOT_LIST = Path("files/input/bot.list")
DEFAULT_TEMPLATE = Path("files/input/template.xlsx")
DEFAULT_OUTPUT_DIR = Path("output")
DEFAULT_DOWNLOAD_DIR = Path("downloads")
DEFAULT_HOLDER_PREFIX = "index-bucket-holder"

REPORT_COLUMNS = [
    "trade_id",
    "broker_order_id",
    "exchange_order_id",
    "instrument",
    "instrument_key",
    "side",
    "entry",
    "exit",
    "trailed",
    "timestamp",
    "qty",
    "amount",
]

FIELD_ALIASES = {
    "trade_id": [
        "trade_id",
        "tradeid",
        "trade.id",
        "id",
        "tag",
        "order_tag",
        "strategy_trade_id",
        "strategytradeid",
    ],
    "broker_order_id": [
        "broker_order_id",
        "brokerorderid",
        "broker_orderid",
        "entry_order_ids",
        "entryorderids",
        "entry_order_refs.order_id",
        "entryorderrefs.orderid",
        "order_id",
        "orderid",
    ],
    "exchange_order_id": [
        "exchange_order_id",
        "exchangeorderid",
        "entry_exchange_order_ids",
        "entryexchangeorderids",
        "entry_order_refs.exchange_order_id",
        "entryorderrefs.exchangeorderid",
    ],
    "instrument": [
        "instrument",
        "tradingsymbol",
        "trading_symbol",
        "symbol",
        "name",
        "instrument_name",
    ],
    "instrument_key": [
        "instrument_key",
        "instrumentkey",
        "instrument_token",
        "instrumenttoken",
        "exchange_token",
        "token",
        "key",
    ],
    "side": [
        "side",
        "transaction_type",
        "transactiontype",
        "action",
        "order_side",
        "orderside",
    ],
    "entry": [
        "entry",
        "entry_price",
        "entryprice",
        "buy_price",
        "buyprice",
        "average_price",
        "averageprice",
        "avg_price",
        "avgprice",
        "price",
    ],
    "exit": [
        "exit",
        "exit_price",
        "exitprice",
        "sell_price",
        "sellprice",
        "exit_average_price",
        "exitaverageprice",
    ],
    "trailed": [
        "trailed",
        "trail",
        "is_trailed",
        "istrailed",
        "trailing_stoploss",
        "trailingstoploss",
        "trailing_sl",
        "trail_sl",
        "tsl_active",
        "tslactive",
    ],
    "timestamp": [
        "timestamp",
        "ts",
        "created_at",
        "createdat",
        "created_time",
        "createdtime",
        "entry_time",
        "entrytime",
        "entry_timestamp",
        "entrytimestamp",
        "trade_time",
        "tradetime",
        "time",
        "date",
    ],
    "qty": [
        "qty",
        "quantity",
        "filled_quantity",
        "filledquantity",
        "filled_qty",
        "filledqty",
        "order_quantity",
        "orderquantity",
    ],
    "amount": [
        "amount",
        "value",
        "order_value",
        "ordervalue",
        "filled_value",
        "filledvalue",
        "turnover",
    ],
}

SECTION_BY_BOT = {
    "firebot": {
        "title_row": 3,
        "header_row": 5,
        "data_start": 6,
        "data_end": 12,
        "total_row": 13,
        "observation_start": 15,
        "observation_end": 18,
        "table": "Table26",
    },
    "haemabot": {
        "title_row": 22,
        "header_row": 24,
        "data_start": 25,
        "data_end": 31,
        "total_row": 32,
        "observation_start": 34,
        "observation_end": 37,
        "table": "Table2",
    },
    "trendobot": {
        "title_row": 39,
        "header_row": 41,
        "data_start": 42,
        "data_end": 49,
        "total_row": 50,
        "observation_start": 53,
        "observation_end": 56,
        "table": "Table27",
    },
    "titanbot": {
        "title_row": 60,
        "header_row": 62,
        "data_start": 63,
        "data_end": 70,
        "total_row": 71,
        "observation_start": 74,
        "observation_end": 77,
        "table": "Table274",
    },
    "fibobot": {
        "title_row": 81,
        "header_row": 83,
        "data_start": 84,
        "data_end": 90,
        "total_row": 91,
        "observation_start": 93,
        "observation_end": 96,
        "table": "Table2742",
    },
}
